#!/usr/bin/env bash

# Copyright 2026 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Vendors loadbalancer/v1/loadbalancer.proto from the loadbalancer-api repo and
# regenerates the Go gRPC bindings under pkg/util/lbapi/gen.
#
# loadbalancer-api only publishes Connect-Go stubs, so the grpc-go client and
# message types are generated here. buf, protoc-gen-go and protoc-gen-go-grpc
# are installed at pinned versions into a scratch directory; nothing is
# installed system-wide. Network access is needed for the tools and for the
# buf.build/bufbuild/protovalidate module the proto imports.
#
# Usage:
#   hack/update-lbapi-proto.sh [path/to/loadbalancer.proto]

set -euo pipefail

BUF_VERSION="${BUF_VERSION:-v1.73.0}"
PROTOC_GEN_GO_VERSION="${PROTOC_GEN_GO_VERSION:-v1.36.11}"
PROTOC_GEN_GO_GRPC_VERSION="${PROTOC_GEN_GO_GRPC_VERSION:-v1.6.2}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
UPSTREAM_PROTO="${1:-${REPO_ROOT}/../loadbalancer-api/proto/loadbalancer/v1/loadbalancer.proto}"

# The descriptor path is baked into the generated code and is the key in the
# global proto registry, so the proto has to sit at this exact path inside the
# buf module.
PROTO_PATH="pkg/util/lbapi/proto/loadbalancer.proto"
GO_MODULE="k8s.io/cloud-provider-openstack"
GEN_DIR="pkg/util/lbapi/gen"
GO_PACKAGE="${GO_MODULE}/${GEN_DIR};loadbalancerv1"

[ -f "$UPSTREAM_PROTO" ] || { echo "upstream proto not found: $UPSTREAM_PROTO" >&2; exit 1; }

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

TOOLS_BIN="${WORK_DIR}/bin"
mkdir -p "$TOOLS_BIN"
GOBIN="$TOOLS_BIN" go install "github.com/bufbuild/buf/cmd/buf@${BUF_VERSION}"
GOBIN="$TOOLS_BIN" go install "google.golang.org/protobuf/cmd/protoc-gen-go@${PROTOC_GEN_GO_VERSION}"
GOBIN="$TOOLS_BIN" go install "google.golang.org/grpc/cmd/protoc-gen-go-grpc@${PROTOC_GEN_GO_GRPC_VERSION}"
export PATH="${TOOLS_BIN}:${PATH}"

mkdir -p "$(dirname "${REPO_ROOT}/${PROTO_PATH}")" "${REPO_ROOT}/${GEN_DIR}"
cp "$UPSTREAM_PROTO" "${REPO_ROOT}/${PROTO_PATH}"

# buf is run in a throwaway workspace rather than against the repo so that no
# buf.yaml/buf.lock has to live in the tree.
BUF_DIR="${WORK_DIR}/module"
mkdir -p "$(dirname "${BUF_DIR}/${PROTO_PATH}")"
cp "${REPO_ROOT}/${PROTO_PATH}" "${BUF_DIR}/${PROTO_PATH}"

cat >"${BUF_DIR}/buf.yaml" <<'EOF'
version: v2
modules:
  - path: .
deps:
  - buf.build/bufbuild/protovalidate
EOF

# The lock pins the protovalidate module. Prefer the upstream repo's own lock;
# the embedded copy is the fallback for when only the .proto is available.
UPSTREAM_LOCK="$(cd "$(dirname "$UPSTREAM_PROTO")/../../.." 2>/dev/null && pwd)/buf.lock"
if [ -f "$UPSTREAM_LOCK" ]; then
	cp "$UPSTREAM_LOCK" "${BUF_DIR}/buf.lock"
else
	cat >"${BUF_DIR}/buf.lock" <<'EOF'
# Generated by buf. DO NOT EDIT.
version: v2
deps:
  - name: buf.build/bufbuild/protovalidate
    commit: 50325440f8f24053b047484a6bf60b76
    digest: b5:74cb6f5c0853c3c10aafc701614194bbd63326bdb8ef4068214454b8894b03ba4113e04b3a33a8321cdf05336e37db4dc14a5e2495db8462566914f36086ba31
EOF
fi

cat >"${BUF_DIR}/buf.gen.yaml" <<EOF
version: v2
plugins:
  - local: protoc-gen-go
    out: .
    opt:
      - module=${GO_MODULE}
      - M${PROTO_PATH}=${GO_PACKAGE}
  - local: protoc-gen-go-grpc
    out: .
    opt:
      - module=${GO_MODULE}
      - M${PROTO_PATH}=${GO_PACKAGE}
EOF

(cd "$BUF_DIR" && buf generate)

# Drop the blank import of the protovalidate Go bindings. The buf.validate
# options are documentation on this side: nothing here reads them at runtime,
# they survive in the raw descriptor either way, and keeping the import would
# add a module dependency purely so an unused extension registers itself.
#
# This removes one import line only. Never rewrite anything else in a .pb.go
# with sed: the raw descriptor is length-prefixed and a changed string
# corrupts it.
sed -i '/buf\.build\/gen\/go\/bufbuild\/protovalidate/d' "${BUF_DIR}/${GEN_DIR}/loadbalancer.pb.go"

cp "${BUF_DIR}/${GEN_DIR}/loadbalancer.pb.go" \
	"${BUF_DIR}/${GEN_DIR}/loadbalancer_grpc.pb.go" \
	"${REPO_ROOT}/${GEN_DIR}/"

gofmt -w "${REPO_ROOT}/${GEN_DIR}/loadbalancer.pb.go"

echo "regenerated ${GO_MODULE}/${GEN_DIR} from ${UPSTREAM_PROTO}"
